library: Avoid false positives in pointer validity check
Any pointer other than NULL is valid. The hack to reject pointers less
than 0x8000 in an attempt to catch coding errors (an enum instead of a
pointer to an enum) results in runtime errors. This leads to test
suite failures and package FTBFS bugs. Use normal NULL test for
pointer validity check.

The comment about gcc not giving a warning about the coding error is
not true -- at least for recent versions:

test.c:5:30: error: passing argument 2 of ‘procps_pids_new’ makes pointer from integer without a cast [-Wint-conversion]
    5 |   if (procps_pids_new(&info, PIDS_extra, 3) < 0) {}
      |                              ^~~~~~~~~~
      |                              |
      |                              int
In file included from test.c:1:
/usr/include/libproc2/pids.h:251:65: note: expected ‘enum pids_item *’ but argument is of type ‘int’
  251 | int procps_pids_new   (struct pids_info **info, enum pids_item *items, int numitems);
      |                                                 ~~~~~~~~~~~~~~~~^~~~~

It doesn't give a warning about PIDS_noop, because it corresponds to 0
and giving an enum corresponding to 0 as an alternative to NULL is not
a coding error. But it does give a warning for all other enums. So only
NULL needs to be checked (and should be checked anyway), not all
addresses smaller than 0x8000 which gives false positives.